# This workflow runs for every push to master
name: Push CI
permissions:
  contents: read

on:
  push:
    branches:
      - master

jobs:
  push-ci-js-helpers-test:
    uses: ./.github/workflows/shared-ci.yml
