version: 0.2

batch:
  fast-fail: true 
  build-graph:

    # Lint and specification compliance
    - identifier: compliance
      buildspec: codebuild/compliance.yml

    # Unit Tests
    #NOTE: Unlike the js-esdk we are not testing the browser since we did not
    #explicitly call that out in the previous code build project. Should we be
    #testing the browser since we have the blueprint for it?
    - identifier: testNodejsLatest
      buildspec: codebuild/nodejs_latest.yml
      env:
        image: aws/codebuild/standard:5.0

    # Integration Tests
    - identifier: testVectorsNodejsLatest
      buildspec: codebuild/test_vectors/nodejs_latest.yml
      env:
        variables:
          PUBLISH_LOCAL: "true"
        image: aws/codebuild/standard:5.0

    # Version the project and push git commits and tags
    - identifier: version
      depend-on:
        - compliance
        - testNodejsLatest
        - testVectorsNodejsLatest
      buildspec: codebuild/release/version.yml

    # Publish the release to npm
    - identifier: publish
      depend-on:
        - version
      buildspec: codebuild/release/publish.yml

    # Validate that the published versions are available
    - identifier: validateNodejs
      depend-on:
        - publish
      buildspec: codebuild/test_vectors/nodejs_latest.yml
      env:
        variables:
          PUBLISH_LOCAL: "false"
        image: aws/codebuild/standard:5.0

