version: 0.2

batch:
  fast-fail: true 
  build-graph:
    # Unit Tests
    #NOTE: We need to add browser testing as part of our Unit Tests. Look at the
    #js-esdk for insight on how we do this.
    - identifier: testNodejsLatest
      buildspec: codebuild/nodejs_latest.yml
      env:
        image: aws/codebuild/standard:5.0

    # Test publishing to local Verdaccio server
    - identifier: test_publish
      depend-on:
          - testNodejsLatest
      buildspec: codebuild/test_vectors/test_publish.yml
      env:
        variables:
          CI: "true"
        image: aws/codebuild/standard:5.0

    # Version the project and push git commits and tags
    - identifier: version
      depend-on:
        - testNodejsLatest
        - test_publish
      buildspec: codebuild/release/version.yml

    # Publish the release to npm
    - identifier: publish
      depend-on:
        - version
      buildspec: codebuild/release/publish.yml

    # Validate and test that the published versions are available
    - identifier: validateNodejs
      depend-on:
        - publish
      buildspec: codebuild/test_vectors/test_publish.yml
      env:
        variables:
          CI: "false"
        image: aws/codebuild/standard:5.0

